theme: jekyll-theme-cayman
title: "Natural language interaction with robots"
description: "I can ask a 5 year old to bring me a spoon, and it's likely that a spoon will appear.  We want a robot to do the same."
