theme: jekyll-theme-cayman
title: "Bring Me A Spoon"
description: "Matterport3D Simulator and Room-to-Room (R2R) data for Vision-and-Language Navigation"
google_analytics: UA-62280059-2

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
